package-lock.json
package.json
src/api/index.ts
src/components/drive-planning/freights/freight-dialog.tsx
src/components/drive-planning/freights/freight-tasks.tsx
src/components/drive-planning/freights/freight-units.tsx
src/components/drive-planning/routes/route-dialog.tsx
src/components/generic/toolbar-row.tsx
src/components/layout/side-navigation.tsx
src/components/layout/top-navigation.tsx
src/components/styled/dialog-header.tsx
src/generated/router/routeTree.gen.ts
src/hooks/use-single-click-row-edit-mode.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/main.tsx
src/routes/__root.tsx
src/routes/drive-planning.routes.add-route.tsx
src/routes/drive-planning.routes.tsx
src/theme/index.ts

Feature 19 routes listing

---

index.html
src/components/drive-planning/routes/task-table-row.tsx
src/components/generic/date-picker-with-arrows.tsx
src/components/generic/dialog-header.tsx
src/components/layout/breadcrumbs-bar.tsx
src/components/layout/side-navigation.tsx
src/components/management/customer-site-form.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/main.tsx
src/theme/index.ts

Adds a basic theme and replaces few inline stylings with styled components

theme and various small adjustments and styled components

---

package-lock.json
package.json
src/components/drive-planning/freights/root-freight-dialog.tsx
src/components/drive-planning/routes/routes-table.tsx
src/hooks/use-single-click-cell-edit-mode.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/main.tsx
src/routes/drive-planning.freights.add-freight.tsx
src/routes/drive-planning.routes.add-route.tsx
src/routes/drive-planning.routes.tsx
src/routes/management.customer-sites_.$customerSiteId.modify.tsx
src/routes/management.customer-sites_.add-customer-site_.tsx
src/routes/management.equipment_.$equipmentId.modify.tsx
src/routes/management.equipment_.add-equipment.tsx

Toasts and routes data grid cell edit mode

---

src/components/drive-planning/freights/freight-dialog.tsx
src/components/drive-planning/freights/freight-tasks.tsx
src/components/drive-planning/freights/routes-dropdown.tsx
src/components/drive-planning/routes/route-dialog.tsx
src/components/drive-planning/routes/unallotaced-tasks-drawer.tsx
src/components/generic/date-picker-with-arrows.tsx
src/components/generic/dialog-header.tsx
src/components/generic/toolbar-row.tsx
src/components/layout/side-navigation.tsx
src/components/management/customer-site-form.tsx
src/components/vehicle-list-screen.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/drive-planning.routes.tsx
src/routes/management.customer-sites.tsx
src/routes/management.equipment.tsx
src/theme/index.ts

resolves #32 
And adds some more styles

Various small styling additions - tooltips added

---

src/components/drive-planning/freights/freight-tasks.tsx
src/components/drive-planning/routes/route-dialog.tsx
src/routes/drive-planning.routes.add-route.tsx
src/routes/drive-planning.routes.tsx

Added order number and fixed add route dialog form logic

---

src/localization/locales/fi.json
src/routes/vehicle-list.map-view.tsx
src/routes/vehicle-list.vehicles.tsx

Feature 39 truck markers on map

---

src/components/layout/breadcrumbs-bar.tsx
src/components/layout/top-navigation.tsx
src/components/vehicles/vehicleInfoBar.tsx
src/generated/router/routeTree.gen.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/vehicle-list.map-view.tsx
src/routes/vehicle-list.vehicles.tsx
src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
src/utils/time-utils.ts

Added vehicle detalis view

---

src/components/drive-planning/routes/routes-table.tsx
src/components/drive-planning/routes/unallotaced-tasks-drawer.tsx
src/components/generic/generic-data-grid.tsx
src/components/layout/view-container.tsx
src/components/management/equipment.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/__root.tsx
src/routes/drive-planning.freights.tsx
src/routes/drive-planning.tsx
src/routes/management.customer-sites.tsx
src/routes/management.equipment.tsx
src/routes/management.tsx
src/routes/management.vehicles.tsx
src/routes/vehicle-list.map-view.tsx
src/routes/vehicle-list.tsx
src/routes/vehicle-list.vehicles.tsx
src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
src/types/index.ts

Layout fixes

---

src/components/vehicles/vehicle-info-bar.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/vehicle-list.vehicles.tsx
src/routes/vehicle-list_.vehicles.$vehicleId.info.tsx
src/utils/localization-utils.ts

Added support for drive states

---

src/components/drive-planning/freights/routes-dropdown.tsx
src/components/drive-planning/routes/expandable-routes-table-row.tsx
src/components/drive-planning/routes/route-dialog.tsx
src/components/drive-planning/routes/routes-table.tsx
src/components/drive-planning/routes/routes-tasks-table.tsx
src/components/drive-planning/routes/unallocated-tasks-drawer.tsx
src/components/generic/date-picker-with-arrows.tsx
src/components/generic/generic-data-grid.tsx
src/hooks/use-queries.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/drive-planning.routes.tsx

Added departure time input to create route dialog and route table edit mode

---

src/components/management/customer-site-form.tsx
src/mapbox/index.ts
src/routes/vehicle-list.map-view.tsx

Resolves #60 
Resolves #61 
- Fixed customer site address autocomplete value clearing on blur
- Fixed customer site address autocomplete not showing results except exact streets
- Restricted customer site address autocomplete search to mapbox streets and addresses and to finnish locations

Fixed truck location marker styling

---

package-lock.json
package.json
src/hooks/use-queries.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/drive-planning.routes.tsx

Added automatic refresh of routes table data

---

src/components/drive-planning/routes/draggable-unallocated-tasks-table-row.tsx
src/components/drive-planning/routes/dragged-task-overlay.tsx
src/components/drive-planning/routes/routes-table.tsx
src/components/drive-planning/routes/routes-tasks-table-row.tsx
src/components/drive-planning/routes/routes-tasks-table.tsx
src/components/drive-planning/routes/task-table-row.tsx
src/components/drive-planning/routes/unallocated-tasks-table.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/drive-planning.freights.tsx
src/routes/drive-planning.routes.tsx
src/theme/index.ts

Feature 69 route freight management styling

---

package-lock.json
package.json
src/components/drive-planning/freights/freight-customer-sites-form.tsx
src/components/drive-planning/freights/freight-dialog.tsx
src/components/drive-planning/freights/freight-tasks.tsx
src/components/drive-planning/freights/freight-units.tsx
src/components/drive-planning/freights/root-freight-dialog.tsx

Bug 72 freight dialog site form validity handling

---

src/components/working-hours/working-hours-document.tsx
src/routes/working-hours_.$employeeId.work-shifts.tsx

Resolves #101 
Needs logic now

Working hours pdf layout and print button

---

src/components/drive-planning/routes/unallocated-tasks-table.tsx
src/components/generic/generic-data-grid.tsx
src/components/layout/top-navigation.tsx
src/components/management/terminals/terminal-form.tsx
src/components/management/terminals/terminal.tsx
src/generated/router/routeTree.gen.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/drive-planning.routes.add.tsx
src/routes/drive-planning.routes.tsx
src/routes/management.customer-sites_.$siteId.modify.tsx
src/routes/management.customer-sites_.add.tsx
src/routes/management.employees.tsx
src/routes/management.employees_.add.tsx
src/routes/management.equipment.tsx
src/routes/management.equipment_.add.tsx
src/routes/management.holidays.add.tsx
src/routes/management.holidays.tsx
src/routes/management.terminals.tsx
src/routes/management.terminals_.$siteId.modify.tsx
src/routes/management.terminals_.add.tsx
src/routes/management.tsx
src/utils/data-validation-utils.ts

RowClicks added
Refactored naming
resolves #115

Terminal listing and creation

---

src/localization/locales/fi.json
src/routes/vehicles_.$truckId.details.tsx
src/utils/localization-utils.ts

Fix drive status localizations

---

src/components/auth/auth-provider.tsx
src/components/drive-planning/freights/freight-dialog.tsx
src/components/drive-planning/freights/freight-tasks.tsx
src/components/drive-planning/routes/route-dialog.tsx
src/components/drive-planning/routes/routes-table.tsx
src/components/drive-planning/routes/routes-tasks-table-row.tsx
src/components/drive-planning/routes/task-table-row.tsx
src/components/drive-planning/routes/unallocated-tasks-table.tsx
src/components/management/customer-sites/customer-site.tsx
src/components/management/employees/employee.tsx
src/components/management/sensors.tsx
src/components/management/terminals/terminal.tsx
src/components/management/terminals/thermometers.tsx
src/components/working-hours/work-shift-dialog.tsx
src/generated/client/models/EmployeeWorkShift.ts
src/routes/working-hours_.$employeeId.work-shifts.tsx

Resolves #132 
- Also fixed listing workshifts and added default max value to all listing queries

Bugfix 132 terminal form bugfixes

---

src/components/management/equipments/equipment-form.tsx
src/components/management/terminals/terminal.tsx
src/components/management/terminals/thermometers-table.tsx
src/components/management/terminals/thermometers.tsx
src/localization/locales/en.json
src/localization/locales/fi.json

resolves #134 
UI layout and dialogs. Does not include functionality

Terminal devices list and table

---

src/components/layout/top-navigation.tsx
src/components/terminals/temperature-rows.tsx
src/components/terminals/terminal-item.tsx
src/generated/router/routeTree.gen.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/terminals.index.tsx
src/theme/index.ts

Terminals view with terminals

---

src/api/index.ts
src/hooks/use-queries.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/working-hours_.$employeeId.work-shifts.tsx

Added support for creating payroll export

---

src/components/generic/un-archive-button.tsx
src/components/management/employees/employee-form.tsx
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/management.employees.tsx

Feature 148 archived users listing

---

src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/vehicles_.$truckId.details.tsx

Feature 150 truck details driver information

---

biome.json
package-lock.json
package.json
src/api/index.ts
src/components/drive-planning/freights/freight-units.tsx
src/components/layout/breadcrumbs-bar.tsx
src/components/layout/top-navigation.tsx
src/components/management/thermal-monitors/thermal-monitor-form-dialog.tsx
src/components/management/thermal-monitors/thermal-monitor-form-monitor-step.tsx
src/components/management/thermal-monitors/thermal-monitor-form-paging-policies-step.tsx
src/components/management/thermal-monitors/thermal-monitor-form-schedule-step.tsx
src/generated/client/models/SalaryPeriodTotalWorkHours.ts
src/generated/router/routeTree.gen.ts
src/hooks/use-queries.ts
src/localization/locales/en.json
src/localization/locales/fi.json
src/routes/incidents.tsx
src/routes/management.thermal-monitors.$thermalMonitorId.modify.tsx
src/routes/management.thermal-monitors.add.tsx
src/utils/data-validation-utils.ts
tsconfig.json
vite.config.ts

Feature 165 incidents
